# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: billomat-rb 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "billomat-rb"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ronald Brachetti"]
  s.date = "2014-05-03"
  s.description = "A neat ruby library for interacting with the RESTfull API of billomat"
  s.email = "rb@ronald-becher.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".document",
    "CHANGES.textile",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "TODO.textile",
    "VERSION.yml",
    "billomat-rb.gemspec",
    "billomat-rb.iml",
    "examples/example.rb",
    "lib/billomat-rb.rb",
    "lib/billomat/articles.rb",
    "lib/billomat/clients.rb",
    "lib/billomat/confirmation.rb",
    "lib/billomat/invoice.rb",
    "lib/billomat/myself.rb",
    "lib/billomat/offer.rb",
    "lib/billomat/reminder.rb",
    "lib/billomat/role.rb",
    "lib/billomat/settings.rb",
    "lib/billomat/template.rb",
    "lib/billomat/unit.rb",
    "lib/billomat/users.rb",
    "test/helper.rb",
    "test/test_billomat-rb.rb"
  ]
  s.homepage = "http://github.com/rbecher/billomat-rb"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Ruby library for interacting with the RESTfull billomat api."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.17"])
      s.add_runtime_dependency(%q<activeresource>, ["~> 3.2.17"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.2.17"])
      s.add_dependency(%q<activeresource>, ["~> 3.2.17"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.2.17"])
    s.add_dependency(%q<activeresource>, ["~> 3.2.17"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

